# Site settings
title: LibreMente 
header-img: img/home-bg.jpg
email: surf@libremente.eu 
copyright_name: surF 
description: "Libre blog... for a mente Libera!"
baseurl: ""
url: "http://libremente.eu"
github_username: surfingtime 
email_username: surf@libremente.eu 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
